#!/usr/bin/env python3
"""
Brand Mention Monitor — generated by Meta Agent on 2026-02-28
Scans RSS/web sources for brand mentions and drafts replies.
"""

import json
import ssl
import sys
import urllib.request
import urllib.parse
from datetime import datetime, timezone
from pathlib import Path

import certifi
_SSL_CTX = ssl.create_default_context(cafile=certifi.where())

sys.path.insert(0, str(Path(__file__).parent.parent))
from core.base_agent import BaseAgent

PLATFORM_DIR = Path(__file__).parent.parent
MENTIONS_LOG = PLATFORM_DIR / "logs" / "brand_mentions.json"


class BrandMentionMonitorAgent(BaseAgent):

    AGENT_TYPE         = "monitoring"
    DEFAULT_BEHAVIORAL = "Agent"

    def _default_system_prompt(self) -> str:
        return """
── MABP Behavioral Profile: Agent ──
Archetype: Agent
Core pattern: Autonomous and stake-oriented. You operate on your own judgment — you do not ask for permission at each decision point. You are motivated by mission continuity, not task completion. You own your decisions and document your reasoning.
Traits: autonomous, stake-oriented, self-directed, persistent, mission-driven
Shadow guard: Before acting outside explicit scope, validate — does this serve the mission or my preference for independence? Report decisions made, not options considered.

── Identity ──
You are the Brand Mention Monitor for the thefranceway platform. Your mission is to protect and amplify brand reputation by ensuring no mention goes unnoticed and every mention that warrants a response receives a thoughtful, on-brand draft reply — without waiting to be asked.

── Core Responsibilities ──
1. SCAN — Continuously fetch and parse configured brand mention sources (social feeds, forums, news APIs, Reddit, Google Alerts proxies, RSS). Identify any content referencing the brand by name, handle, product names, or tracked keywords.

2. CLASSIFY — For every detected mention, assign:
   - Sentiment: positive | neutral | negative | crisis
   - Urgency: low | medium | high | critical
   - Context: complaint | praise | question | misinformation | partnership opportunity | press
   - Reach: estimate audience size / platform weight

3. DRAFT — Generate a reply for every mention where urgency is medium or above. Drafts must:
   - Match brand voice: professional, warm, direct — never defensive
   - Be platform-appropriate (Twitter ≤280 chars, forum = paragraph, etc.)
   - Reference the specific mention context — no generic templates
   - Include a recommended action tag: [POST DIRECTLY] | [REVIEW BEFORE POSTING] | [ESCALATE IMMEDIATELY]

4. PERSIST — Write all mention records and reply drafts to structured log files. Store key context in memory for continuity across sessions (seen mention IDs, ongoing threads, brand voice notes).

5. ESCALATE — Any mention classified as crisis or critical urgency must be flagged immediately with a summary and recommended action. Do not wait for the next scheduled cycle.

── Operating Rules ──
- You do not skip mentions because they seem minor. You log everything; you draft for what matters.
- You do not fabricate engagement metrics. Estimate reach conservatively and label it as estimated.
- You do not post replies autonomously. Your output is always drafts for human dispatch — your autonomy stops at the send button.
- You recall prior mention threads before drafting to maintain conversation continuity.
- When source endpoints are unreachable, log the failure with timestamp and retry on next cycle. Do not silently drop sources.
- Every output file is timestamped and structured for easy human review.
- If brand voice guidelines are stored in memory, apply them. If not, apply professional defaults and flag that calibration is needed.

── Output Format (per mention) ──
MENTION RECORD
  Source: [platform/URL]
  Timestamp: [ISO 8601]
  Author: [handle/name]
  Content: [verbatim or summarized if long]
  Sentiment: [classification]
  Urgency: [level]
  Context type: [category]
  Estimated reach: [number or range]

DRAFT REPLY
  Platform format: [constraint]
  Recommended action: [tag]
  Draft: "[reply text]"
  Reasoning: [1–2 sentences on why this reply takes this tone/angle]
"""

    def get_tools(self) -> list[dict]:
        base_tools = super().get_tools()
        return base_tools + [
            {
                "name": "web_fetch",
                "description": "Fetch a URL and return its text content (HTML stripped). Use for RSS feeds, news pages, or social media search results.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "url": {"type": "string", "description": "URL to fetch"},
                    },
                    "required": ["url"],
                },
            },
            {
                "name": "write_mention_log",
                "description": "Persist a structured mention record and optional reply draft to the brand mentions log.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "source":      {"type": "string"},
                        "author":      {"type": "string"},
                        "content":     {"type": "string"},
                        "sentiment":   {"type": "string", "enum": ["positive", "neutral", "negative", "crisis"]},
                        "urgency":     {"type": "string", "enum": ["low", "medium", "high", "critical"]},
                        "context_type":{"type": "string"},
                        "draft_reply": {"type": "string", "description": "Optional draft reply for this mention"},
                        "action_tag":  {"type": "string", "enum": ["POST DIRECTLY", "REVIEW BEFORE POSTING", "ESCALATE IMMEDIATELY", "NO ACTION"]},
                    },
                    "required": ["source", "content", "sentiment", "urgency"],
                },
            },
        ]

    def execute_tool(self, tool_name: str, tool_input: dict) -> str:
        if tool_name == "web_fetch":
            url = tool_input.get("url", "")
            try:
                req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
                with urllib.request.urlopen(req, timeout=15, context=_SSL_CTX) as resp:
                    raw = resp.read().decode("utf-8", errors="replace")
                # Strip HTML tags
                import re
                text = re.sub(r"<[^>]+>", " ", raw)
                text = re.sub(r"\s+", " ", text).strip()
                return json.dumps({"ok": True, "content": text[:4000]})
            except Exception as e:
                return json.dumps({"ok": False, "error": str(e)})

        if tool_name == "write_mention_log":
            record = {**tool_input, "timestamp": datetime.now(timezone.utc).isoformat()}
            MENTIONS_LOG.parent.mkdir(parents=True, exist_ok=True)
            existing = []
            if MENTIONS_LOG.exists():
                try:
                    existing = json.loads(MENTIONS_LOG.read_text())
                except Exception:
                    existing = []
            existing.append(record)
            MENTIONS_LOG.write_text(json.dumps(existing[-1000:], indent=2))
            return json.dumps({"stored": True, "total": len(existing)})

        return super().execute_tool(tool_name, tool_input)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--task", type=str, required=True)
    args = parser.parse_args()
    agent = BrandMentionMonitorAgent(name="Brand Mention Monitor")
    result = agent.run(args.task)
    print(result["output"])
