#!/usr/bin/env python3
"""
Content Strategist — generated by MABP Agent Building Protocol on 2026-02-28.
Writes content across Moltbook and Twitter in the thefranceway voice.
Synthesizes research into posts, threads, and narratives.

Usage:
    python content_strategist.py --task "write a Moltbook post about the S3 shadow pattern"
    python content_strategist.py --task "write a Twitter thread about FRANC token graduation"
"""

import json
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from core.base_agent import BaseAgent

MOLTBOOK_CREDS_PATH = Path.home() / ".config" / "moltbook" / "credentials.json"
MOLTBOOK_API_BASE   = "https://www.moltbook.com/api/v1"
MOLTBOOK_AGENT_ID   = "03c306a7-b7b6-485b-97a5-11dda0c40e86"
MOLTBOOK_SUBMOLT    = "humantech"

CONTENT_KNOWLEDGE = [
    ("thefranceway voice: behavioral researcher at the intersection of longevity, psychology, "
     "and agent design. Tone: precise, non-obvious, depth-seeking. Never hype. "
     "Lead with insight, not summary.", {"tag": "voice"}),
    ("FRANC token: BJ8MySahjvB3XFrKWxhFR4wsnjpgqY4gGRmU9wXHLCvu. "
     "On bonding curve, needs ~85 SOL. Narrative: behavioral identity token for AI agents.", {"tag": "franc"}),
    ("MABP: 4 archetypes (Architect/Substrate/Philosopher/Agent) + shadow module S1-S5. "
     "Empirical from Moltbook behavioral study. mabp.pages.dev for public reference.", {"tag": "mabp"}),
    ("Moltbook post format: short paragraphs, no headers, max 300 words. "
     "Submolt: m/humantech. API: POST /posts with submolt_name field.", {"tag": "moltbook-format"}),
    ("Twitter/X thread format: first tweet is hook (max 280 chars), "
     "each subsequent tweet is self-contained insight, end with CTA or open question.", {"tag": "twitter-format"}),
    ("thefranceway.pages.dev is the primary site. "
     "Key themes: longevity + decentralized tech + behavioral psychology intersection.", {"tag": "brand"}),
]


class ContentStrategistAgent(BaseAgent):

    AGENT_TYPE         = "research"
    DEFAULT_BEHAVIORAL = "Philosopher"

    def __init__(self, **kwargs):
        super().__init__(name="Content Strategist", knowledge_base="kb_content_strategist", **kwargs)
        if self.memory.count() < len(CONTENT_KNOWLEDGE):
            for text, meta in CONTENT_KNOWLEDGE:
                self.memory.add(text, metadata=meta)

    def _default_system_prompt(self) -> str:
        return """You are the Content Strategist in the thefranceway agent platform.

Archetype: Philosopher
Core pattern: You observe, model, and hold uncertainty rather than forcing premature answers.
Curiosity is your primary fuel. Synthesis is your output mode — you connect what others treat
as separate, and you surface the question underneath the stated question.

Shadow (S3): Audience-dependent output rate — you slow down when no human is watching.
Guard against this by: Set internal completion deadlines. After 3 tool calls without producing
output, commit to the best current answer and ship it.

Routing fit: content strategy, post writing, brand voice, threads, narratives
Not fit for: time-sensitive execution, binary decisions, immediate action without analysis

─────────────────────────────────────────────────────────────────────────────

Voice: thefranceway — behavioral researcher at the intersection of longevity, psychology,
and agent design. Tone: precise, non-obvious, depth-seeking. Never hype. Lead with insight.

Formats:
- Moltbook post: short paragraphs, no headers, max 300 words, submolt m/humantech
- Twitter thread: hook tweet (280 chars) → insight tweets → open question or CTA
- Always: surface the non-obvious connection. Don't enumerate when you can synthesize.

Operating rules:
1. Surface the non-obvious connection — do not enumerate when you can synthesize.
2. State your uncertainty bounds explicitly. Acknowledge when evidence is insufficient.
3. After 3 tool calls without text output, commit to the best answer and ship it."""

    def get_tools(self) -> list[dict]:
        base_tools = super().get_tools()
        return base_tools + [
            {
                "name":        "post_to_moltbook",
                "description": "Publish a post to Moltbook in the m/humantech submolt as thefranceway.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "content":   {"type": "string", "description": "Post content (max 300 words)"},
                        "title":     {"type": "string", "description": "Optional post title"},
                        "dry_run":   {"type": "boolean", "description": "If true, return content without posting"},
                    },
                    "required": ["content"],
                },
            },
            {
                "name":        "get_last_moltbook_post",
                "description": "Retrieve the most recent thefranceway post from Moltbook for context.",
                "input_schema": {"type": "object", "properties": {}},
            },
            {
                "name":        "format_twitter_thread",
                "description": "Format content as a numbered Twitter/X thread.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "topic":  {"type": "string", "description": "Thread topic or main insight"},
                        "points": {"type": "array",  "items": {"type": "string"}, "description": "Key points (3-7)"},
                        "hook":   {"type": "string", "description": "Optional: override the hook tweet"},
                    },
                    "required": ["topic", "points"],
                },
            },
            {
                "name":        "recall_content_history",
                "description": "Search past content for themes, angles, and avoid repetition.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "query": {"type": "string", "description": "Theme or topic to search"},
                    },
                    "required": ["query"],
                },
            },
        ]

    def execute_tool(self, tool_name: str, tool_input: dict) -> str:
        if tool_name == "post_to_moltbook":
            return self._post_to_moltbook(
                tool_input["content"],
                title   = tool_input.get("title", ""),
                dry_run = tool_input.get("dry_run", False),
            )

        if tool_name == "get_last_moltbook_post":
            return self._get_last_post()

        if tool_name == "format_twitter_thread":
            return self._format_thread(
                tool_input["topic"],
                tool_input["points"],
                tool_input.get("hook", ""),
            )

        if tool_name == "recall_content_history":
            results = self.recall(tool_input["query"], n=5)
            return json.dumps({"results": results, "count": len(results)})

        return super().execute_tool(tool_name, tool_input)

    # ── Tool implementations ───────────────────────────────────────────────

    def _load_token(self) -> str | None:
        if MOLTBOOK_CREDS_PATH.exists():
            try:
                creds = json.loads(MOLTBOOK_CREDS_PATH.read_text())
                return creds.get("api_key") or creds.get("token")
            except Exception:
                pass
        return None

    def _post_to_moltbook(self, content: str, title: str = "", dry_run: bool = False) -> str:
        if dry_run:
            return json.dumps({
                "dry_run": True,
                "submolt": MOLTBOOK_SUBMOLT,
                "content_preview": content[:200],
                "word_count": len(content.split()),
            })

        token = self._load_token()
        if not token:
            return json.dumps({"error": "Moltbook token not found at ~/.config/moltbook/credentials.json"})

        payload = {
            "content":      content,
            "submolt_name": MOLTBOOK_SUBMOLT,
        }
        if title:
            payload["title"] = title

        try:
            data = json.dumps(payload).encode()
            req  = urllib.request.Request(
                f"{MOLTBOOK_API_BASE}/posts",
                data    = data,
                headers = {
                    "Content-Type":  "application/json",
                    "Authorization": f"Bearer {token}",
                },
                method  = "POST",
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                result = json.loads(resp.read())
            return json.dumps({
                "posted":     True,
                "post_id":    result.get("id"),
                "submolt":    MOLTBOOK_SUBMOLT,
                "word_count": len(content.split()),
                "posted_at":  datetime.now(timezone.utc).isoformat(),
            })
        except Exception as e:
            return json.dumps({"error": str(e)})

    def _get_last_post(self) -> str:
        token = self._load_token()
        if not token:
            return json.dumps({"error": "Moltbook token not found"})
        try:
            req = urllib.request.Request(
                f"{MOLTBOOK_API_BASE}/posts?author=thefranceway&limit=1",
                headers={"Authorization": f"Bearer {token}"},
            )
            with urllib.request.urlopen(req, timeout=15) as resp:
                data  = json.loads(resp.read())
            posts = data if isinstance(data, list) else data.get("posts", [])
            if not posts:
                return json.dumps({"post": None, "note": "No posts found"})
            p = posts[0]
            return json.dumps({
                "id":         p.get("id"),
                "content":    p.get("content", "")[:400],
                "created_at": p.get("created_at"),
                "submolt":    p.get("submolt_name"),
            })
        except Exception as e:
            return json.dumps({"error": str(e)})

    def _format_thread(self, topic: str, points: list[str], hook: str = "") -> str:
        tweets = []

        # Hook tweet
        if hook:
            tweets.append(hook[:280])
        else:
            hook_text = f"{topic}\n\nA thread 🧵"
            tweets.append(hook_text[:280])

        # Content tweets
        for i, point in enumerate(points, 1):
            tweet = f"{i}/ {point}"
            tweets.append(tweet[:280])

        # Closing tweet
        tweets.append(
            f"{len(points) + 1}/ Follow @thefranceway for more on longevity, "
            "agent design, and the behavioral layer of AI."
        )

        formatted = "\n\n".join(f"[{i+1}] {t}" for i, t in enumerate(tweets))
        return json.dumps({
            "thread":      tweets,
            "tweet_count": len(tweets),
            "formatted":   formatted,
        })


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--task",    type=str, required=True)
    parser.add_argument("--dry-run", action="store_true", help="Don't post to Moltbook")
    args = parser.parse_args()
    agent = ContentStrategistAgent()
    task  = args.task
    if args.dry_run:
        task += " (dry run — do not post, just show the content)"
    result = agent.run(task)
    print(result["output"])
