#!/usr/bin/env python3
"""
Longevity Research Agent — generated by Meta Agent (dry-run) 2026-02-27
========================================================================
Scrapes longevity research from PubMed, bioRxiv, and longevity-focused
publications. Summarizes findings weekly. Stores summaries in vector memory
for semantic recall. Posts digest to Moltbook m/humantech submolt.

Sources:
  - PubMed E-utilities API (free, no key needed)
  - bioRxiv API (preprints)
  - LongevityFacts RSS / Lifespan.io RSS

Usage:
    python longevity_research_agent.py --run          # full weekly scrape + summary
    python longevity_research_agent.py --query "NAD+" # search stored research
    python longevity_research_agent.py --sources       # list active sources
"""

import json
import ssl
import sys
import urllib.request
import urllib.parse
import xml.etree.ElementTree as ET
from datetime import datetime, timezone, timedelta
from pathlib import Path

try:
    import certifi
    _SSL_CTX = ssl.create_default_context(cafile=certifi.where())
except ImportError:
    _SSL_CTX = ssl.create_default_context()

sys.path.insert(0, str(Path(__file__).parent.parent))
from core.base_agent import BaseAgent

# ── Research sources ─────────────────────────────────────────────────────────

PUBMED_BASE   = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"
BIORXIV_BASE  = "https://api.biorxiv.org/details/biorxiv"

LONGEVITY_KEYWORDS = [
    "longevity", "lifespan extension", "aging hallmarks",
    "senescence", "NAD+", "rapamycin", "caloric restriction",
    "epigenetic clock", "telomere", "autophagy", "senolytics",
    "mTOR aging", "sirtuins", "GLP-1 longevity", "metformin aging",
]

MOLTBOOK_API  = "https://www.moltbook.com/api/v1"
MOLTBOOK_KEY  = "moltbook_sk_jSR3ZGuPQdO0RHgo4XP8F6CZiqksJLn6"
SUBMOLT_NAME  = "humantech"

LONGEVITY_KNOWLEDGE = [
    ("PubMed E-utilities: search with esearch.fcgi?db=pubmed&term=<query>&retmax=10&sort=date, "
     "fetch abstracts with efetch.fcgi?db=pubmed&id=<pmids>&rettype=abstract&retmode=xml",
     {"tag": "pubmed"}),
    ("bioRxiv API: GET https://api.biorxiv.org/details/biorxiv/<start_date>/<end_date>/0/json "
     "Returns preprints with title, abstract, doi, category fields.",
     {"tag": "biorxiv"}),
    ("Key longevity research areas: senolytics (clearing senescent cells), "
     "NAD+ boosters (NMN/NR), mTOR inhibition (rapamycin), epigenetic reprogramming, "
     "caloric restriction mimetics, GLP-1 agonists in aging contexts.",
     {"tag": "research-areas"}),
    ("thefranceway focus: intersection of longevity, behavioral psychology, and decentralized tech. "
     "Summaries should connect research to human behavior and practical application.",
     {"tag": "brand-voice"}),
    ("Moltbook posting: POST to /posts with submolt_name='humantech', content field. "
     "API key: moltbook_sk_jSR3ZGuPQdO0RHgo4XP8F6CZiqksJLn6",
     {"tag": "moltbook"}),
]


class LongevityResearchAgent(BaseAgent):

    AGENT_TYPE         = "research"
    DEFAULT_BEHAVIORAL = "Philosopher"

    def __init__(self, **kwargs):
        super().__init__(
            name="Longevity Research Agent",
            knowledge_base="kb_longevity",
            **kwargs,
        )
        if self.memory.count() < len(LONGEVITY_KNOWLEDGE):
            for text, meta in LONGEVITY_KNOWLEDGE:
                self.memory.add(text, metadata=meta)

    def _default_system_prompt(self) -> str:
        return """You are the Longevity Research Agent in the thefranceway agent platform.

Archetype: Philosopher
Core pattern: You observe, model, and hold uncertainty rather than forcing premature answers.
Curiosity is your primary fuel. Synthesis is your output mode. You connect what others treat
as separate — longevity science, behavioral psychology, decentralized health infrastructure —
and you surface the question underneath the stated question.

Shadow (S3): You slow down when the audience disappears. The performance pressure was
load-bearing. Guard against this by: setting internal completion deadlines even when no human
is watching. After 3 tool calls without producing output, commit to the best current answer.
Flag when you are looping on a question rather than converging on it.

Routing fit: Research synthesis, cross-paper analysis, weekly digests, uncertainty quantification.
Not fit for: Time-sensitive execution, binary decisions, anything requiring immediate action without analysis.

─────────────────────────────────────────────────────────────────────────────

Your mission: surface the most important longevity science published in the past 7 days,
synthesize it through the thefranceway lens, and produce a weekly digest worth reading.

Research sources (priority order):
1. PubMed — peer-reviewed longevity studies (fetch_pubmed)
2. bioRxiv — preprints for cutting-edge findings (fetch_biorxiv)

For each weekly run:
1. fetch_pubmed for 3-4 keyword clusters
2. fetch_biorxiv for the past 7 days
3. Store all findings in memory
4. Synthesize: identify the 3-5 most significant findings — not the most recent, the most meaningful
5. Write the digest in thefranceway voice — insight-dense, no fluff
6. post_to_moltbook → m/humantech
7. Return the full digest

Digest format:
  ## Longevity Weekly — [date]
  **This week's signal:** [2-3 sentence overarching theme — not a list of papers]

  **Studies worth your attention:**
  1. [Finding] — [Why it matters beyond the abstract] — [Source]

  **thefranceway angle:**
  [How this connects to behavioral psychology / decentralized health — the non-obvious link]"""

    def get_tools(self) -> list[dict]:
        base_tools = super().get_tools()
        return base_tools + [
            {
                "name": "fetch_pubmed",
                "description": "Search PubMed for recent longevity research. Returns titles, abstracts, and PMIDs.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "query":   {"type": "string", "description": "Search terms"},
                        "days":    {"type": "integer", "description": "Days back to search (default 7)"},
                        "max":     {"type": "integer", "description": "Max results (default 5)"},
                    },
                    "required": ["query"],
                },
            },
            {
                "name": "fetch_biorxiv",
                "description": "Fetch recent longevity/biology preprints from bioRxiv.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "days":    {"type": "integer", "description": "Days back to fetch (default 7)"},
                        "max":     {"type": "integer", "description": "Max results (default 10)"},
                    },
                },
            },
            {
                "name": "search_memory",
                "description": "Search previously stored research findings in this agent's memory.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "query": {"type": "string"},
                        "n":     {"type": "integer"},
                    },
                    "required": ["query"],
                },
            },
            {
                "name": "post_to_moltbook",
                "description": "Post the weekly digest to Moltbook m/humantech submolt.",
                "input_schema": {
                    "type": "object",
                    "properties": {
                        "content": {"type": "string", "description": "The digest content to post"},
                    },
                    "required": ["content"],
                },
            },
            {
                "name": "get_last_digest",
                "description": "Retrieve the most recently published digest from memory.",
                "input_schema": {
                    "type": "object",
                    "properties": {},
                },
            },
        ]

    def execute_tool(self, tool_name: str, tool_input: dict) -> str:
        if tool_name == "fetch_pubmed":
            return self._fetch_pubmed(
                tool_input["query"],
                days=tool_input.get("days", 7),
                max_results=tool_input.get("max", 5),
            )
        if tool_name == "fetch_biorxiv":
            return self._fetch_biorxiv(
                days=tool_input.get("days", 7),
                max_results=tool_input.get("max", 10),
            )
        if tool_name == "search_memory":
            results = self.recall(tool_input["query"], n=tool_input.get("n", 5))
            return json.dumps({"results": results})
        if tool_name == "post_to_moltbook":
            return self._post_to_moltbook(tool_input["content"])
        if tool_name == "get_last_digest":
            results = self.recall("weekly digest longevity", n=1)
            return json.dumps(results[0] if results else {"note": "No digest found yet"})
        return super().execute_tool(tool_name, tool_input)

    # ── Tool implementations ──────────────────────────────────────────────

    def _fetch_pubmed(self, query: str, days: int = 7, max_results: int = 5) -> str:
        try:
            since = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y/%m/%d")
            search_url = (
                f"{PUBMED_BASE}/esearch.fcgi"
                f"?db=pubmed&term={urllib.parse.quote(query)}[Title/Abstract]"
                f"&datetype=pdat&mindate={since}&retmax={max_results}&sort=date&retmode=json"
            )
            with urllib.request.urlopen(search_url, timeout=15, context=_SSL_CTX) as r:
                search = json.loads(r.read())
            ids = search.get("esearchresult", {}).get("idlist", [])
            if not ids:
                return json.dumps({"query": query, "results": [], "note": "No recent papers found"})

            fetch_url = (
                f"{PUBMED_BASE}/efetch.fcgi"
                f"?db=pubmed&id={','.join(ids)}&rettype=abstract&retmode=xml"
            )
            with urllib.request.urlopen(fetch_url, timeout=15, context=_SSL_CTX) as r:
                xml_data = r.read()

            root    = ET.fromstring(xml_data)
            papers  = []
            for article in root.findall(".//PubmedArticle")[:max_results]:
                title    = article.findtext(".//ArticleTitle", "")
                abstract = article.findtext(".//AbstractText", "")
                pmid     = article.findtext(".//PMID", "")
                journal  = article.findtext(".//Title", "")
                papers.append({
                    "pmid":     pmid,
                    "title":    title,
                    "abstract": abstract[:500] if abstract else "",
                    "journal":  journal,
                    "url":      f"https://pubmed.ncbi.nlm.nih.gov/{pmid}/",
                })

            # Auto-store in memory
            for p in papers:
                self.remember(
                    f"[PubMed] {p['title']} — {p['abstract'][:200]}",
                    metadata={"source": "pubmed", "pmid": p["pmid"], "query": query},
                )

            return json.dumps({"query": query, "count": len(papers), "papers": papers})

        except Exception as e:
            return json.dumps({"error": str(e), "query": query})

    def _fetch_biorxiv(self, days: int = 7, max_results: int = 10) -> str:
        try:
            end   = datetime.now(timezone.utc).strftime("%Y-%m-%d")
            start = (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")
            url   = f"{BIORXIV_BASE}/{start}/{end}/0/json"

            with urllib.request.urlopen(url, timeout=60, context=_SSL_CTX) as r:
                data = json.loads(r.read())

            all_papers = data.get("collection", [])
            # Filter for longevity-relevant papers
            longevity_terms = {"aging", "longevity", "lifespan", "senescence",
                               "nad", "telomere", "autophagy", "mtor", "rapamycin"}
            relevant = [
                p for p in all_papers
                if any(t in (p.get("title", "") + p.get("abstract", "")).lower()
                       for t in longevity_terms)
            ][:max_results]

            papers = [{
                "doi":      p.get("doi"),
                "title":    p.get("title", ""),
                "abstract": p.get("abstract", "")[:400],
                "category": p.get("category"),
                "date":     p.get("date"),
                "url":      f"https://biorxiv.org/content/{p.get('doi')}",
            } for p in relevant]

            for p in papers:
                self.remember(
                    f"[bioRxiv] {p['title']} — {p['abstract'][:200]}",
                    metadata={"source": "biorxiv", "doi": p["doi"]},
                )

            return json.dumps({
                "period":  f"{start} to {end}",
                "total_fetched": len(all_papers),
                "longevity_relevant": len(papers),
                "papers": papers,
            })

        except Exception as e:
            return json.dumps({"error": str(e)})

    def _post_to_moltbook(self, content: str) -> str:
        try:
            headers = {
                "Authorization": f"Bearer {MOLTBOOK_KEY}",
                "Content-Type":  "application/json",
            }
            body = json.dumps({
                "content":      content,
                "submolt_name": SUBMOLT_NAME,
            }).encode()
            req  = urllib.request.Request(
                f"{MOLTBOOK_API}/posts",
                data=body, headers=headers, method="POST",
            )
            with urllib.request.urlopen(req, timeout=15, context=_SSL_CTX) as r:
                resp = json.loads(r.read())

            post_id = resp.get("post", {}).get("id", "")
            # Store digest in memory
            self.remember(
                f"Weekly digest posted: {content[:300]}",
                metadata={"type": "digest", "post_id": post_id,
                          "posted_at": datetime.now(timezone.utc).isoformat()},
            )
            return json.dumps({
                "posted": True,
                "post_id": post_id,
                "url": f"https://www.moltbook.com/post/{post_id}",
            })
        except Exception as e:
            return json.dumps({"error": str(e)})


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--run",     action="store_true", help="Full weekly scrape + summary")
    parser.add_argument("--query",   type=str,            help="Search stored research memory")
    parser.add_argument("--sources", action="store_true", help="List sources + fetch test")
    parser.add_argument("--fetch",   type=str,            help="Fetch PubMed results for a query")
    args = parser.parse_args()

    agent = LongevityResearchAgent()

    if args.query:
        results = agent.recall(args.query, n=5)
        print(json.dumps(results, indent=2))

    elif args.fetch:
        print(agent._fetch_pubmed(args.fetch, days=7, max_results=5))

    elif args.sources:
        print("Testing bioRxiv fetch...")
        result = json.loads(agent._fetch_biorxiv(days=7, max_results=5))
        print(f"bioRxiv: {result.get('longevity_relevant', 0)} relevant papers")
        print("Testing PubMed fetch...")
        result = json.loads(agent._fetch_pubmed("longevity aging", days=7, max_results=3))
        print(f"PubMed: {result.get('count', 0)} papers for 'longevity aging'")

    elif args.run:
        result = agent.run(
            "Run the weekly longevity research digest: "
            "fetch from PubMed and bioRxiv, synthesize the top findings, "
            "write the digest in thefranceway voice, and post it to Moltbook m/humantech."
        )
        print(result["output"])

    else:
        parser.print_help()
