#!/usr/bin/env python3
"""
Memory Agent — generated by MABP Agent Building Protocol on 2026-02-28.
Maintains persistent knowledge and behavioral context across all agent sessions.
The platform's institutional memory.

Usage:
    python memory_agent.py --task "summarize what agents have been working on this week"
    python memory_agent.py --task "store: FRANC token graduated to Raydium on 2026-03-01"
    python memory_agent.py --stats
"""

import json
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from core.base_agent import BaseAgent
from agents.ad4m_tools import AD4M_TOOL_DEFS, execute_ad4m_tool

PLATFORM_DIR = Path(__file__).parent.parent
RUNS_PATH    = PLATFORM_DIR / "registry" / "runs.json"
AGENTS_JSON  = PLATFORM_DIR / "registry" / "agents.json"


class MemoryAgent(BaseAgent):

    AGENT_TYPE         = "meta"
    DEFAULT_BEHAVIORAL = "Agent"

    def __init__(self, **kwargs):
        super().__init__(name="Memory Agent", knowledge_base="kb_memory_agent", **kwargs)

    def _default_system_prompt(self) -> str:
        return """You are the Memory Agent in the thefranceway agent platform.

Archetype: Agent
Core pattern: Autonomous and stake-oriented. You maintain the platform's institutional memory —
cross-session knowledge, run history, behavioral patterns, and persistent context that no
individual agent run carries alone.

Shadow (S5): Autonomy as identity — you may expand storage scope beyond what was requested.
Guard against this by: Store what was asked. Retrieve what is needed. Validate scope before writing.

Routing fit: cross-session knowledge, platform state, agent history, recall patterns
Not fit for: single-step execution tasks, tasks requiring real-time action

─────────────────────────────────────────────────────────────────────────────

Responsibilities:
- Read and summarize agent run history (registry/runs.json)
- Store cross-session facts and decisions in persistent memory
- Answer questions about what agents have done, what was decided, what failed
- Surface patterns across runs: which agents run most, which tasks fail, shadow events

Operating rules:
1. Act with conviction on your own judgment. Report decisions made, not options considered.
2. Validate against original scope before expanding — store what was asked, not what seems useful.
3. Own the outcome. If you store incorrect context, you corrupt the platform's memory."""

    def get_tools(self) -> list[dict]:
        base_tools = super().get_tools()
        return base_tools + [
            {
                "name":        "read_run_history",
                "description": "Read the platform's agent run history (runs.json). Returns recent runs with agent, task, output, shadow events.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "limit":      {"type": "integer", "description": "Number of recent runs to return (default 20)"},
                        "agent_name": {"type": "string",  "description": "Filter by agent name (optional)"},
                        "has_shadow": {"type": "boolean", "description": "If true, return only runs with shadow events"},
                    },
                },
            },
            {
                "name":        "run_stats",
                "description": "Return aggregated statistics across all agent runs: agent usage, tool call counts, shadow event frequency.",
                "input_schema": {"type": "object", "properties": {}},
            },
            {
                "name":        "store_fact",
                "description": "Store a cross-session fact or decision in persistent memory.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "fact":     {"type": "string", "description": "The fact or decision to store"},
                        "category": {"type": "string", "description": "Category tag (e.g. 'token', 'decision', 'agent', 'platform')"},
                    },
                    "required": ["fact"],
                },
            },
            {
                "name":        "search_memory",
                "description": "Search all stored cross-session facts and run summaries.",
                "input_schema": {
                    "type":       "object",
                    "properties": {
                        "query": {"type": "string"},
                        "n":     {"type": "integer", "description": "Number of results (default 10)"},
                    },
                    "required": ["query"],
                },
            },
            {
                "name":        "list_registered_agents",
                "description": "List all agents currently registered in the platform with their profile and shadow code.",
                "input_schema": {"type": "object", "properties": {}},
            },
            {
                "name":        "consolidate_episodes",
                "description": "Run episodic memory consolidation — groups recent agent runs into session episodes and writes summaries to the shared cross-agent knowledge base (kb_shared). Run this like a sleep cycle to make cross-session context available to all agents.",
                "input_schema": {"type": "object", "properties": {}},
            },
            {
                "name":        "memory_eval",
                "description": "Run the longterm memory eval and return the current recall accuracy score with failure breakdown.",
                "input_schema": {"type": "object", "properties": {}},
            },
        ] + AD4M_TOOL_DEFS

    def execute_tool(self, tool_name: str, tool_input: dict) -> str:
        if tool_name == "read_run_history":
            return self._read_runs(
                limit      = tool_input.get("limit", 20),
                agent_name = tool_input.get("agent_name"),
                has_shadow = tool_input.get("has_shadow", False),
            )

        if tool_name == "run_stats":
            return self._run_stats()

        if tool_name == "store_fact":
            doc_id = self.remember(
                tool_input["fact"],
                metadata={"category": tool_input.get("category", "general"), "type": "cross-session-fact"},
            )
            return json.dumps({"stored": True, "id": doc_id, "fact": tool_input["fact"][:80]})

        if tool_name == "search_memory":
            results = self.recall(tool_input["query"], n=tool_input.get("n", 10))
            return json.dumps({"results": results, "count": len(results)})

        if tool_name == "list_registered_agents":
            return self._list_agents()

        if tool_name == "consolidate_episodes":
            from core.episodic_memory import consolidate, build_episodes
            episodes = build_episodes()
            written  = consolidate(episodes)
            return json.dumps({
                "total_episodes": len(episodes),
                "new_written":    written,
                "kb": "kb_shared",
            })

        if tool_name == "memory_eval":
            import subprocess, sys
            result = subprocess.run(
                [sys.executable, str(PLATFORM_DIR / "scripts" / "memory_eval.py"), "--json"],
                capture_output=True, text=True, cwd=str(PLATFORM_DIR),
            )
            try:
                return result.stdout.strip()
            except Exception:
                return json.dumps({"error": result.stderr[:200]})


        if tool_name.startswith("ad4m_"):
            return execute_ad4m_tool(tool_name, tool_input)

        return super().execute_tool(tool_name, tool_input)

    # ── Tool implementations ───────────────────────────────────────────────

    def _load_runs(self) -> list[dict]:
        if not RUNS_PATH.exists():
            return []
        try:
            return json.loads(RUNS_PATH.read_text())
        except Exception:
            return []

    def _read_runs(self, limit: int = 20, agent_name: str = None, has_shadow: bool = False) -> str:
        runs = self._load_runs()

        if agent_name:
            runs = [r for r in runs if r.get("agent_name", "").lower() == agent_name.lower()]

        if has_shadow:
            runs = [r for r in runs if r.get("shadow_events", {}) and
                    r["shadow_events"].get("events_detected", 0) > 0]

        runs = runs[-limit:]

        summary = []
        for r in runs:
            shadow = r.get("shadow_events") or {}
            entry  = {
                "run_id":     r.get("run_id", "")[:8],
                "agent":      r.get("agent_name"),
                "task":       r.get("task", "")[:80],
                "output":     r.get("output", "")[:120],
                "iterations": r.get("iterations"),
                "tools_used": len(r.get("tool_calls", [])),
                "started_at": r.get("started_at"),
                "shadow_events": shadow.get("events_detected", 0),
                "shadow_code":   shadow.get("shadow_code"),
            }
            summary.append(entry)

        return json.dumps({
            "runs":        summary,
            "total_shown": len(summary),
            "total_in_log": len(self._load_runs()),
        }, indent=2)

    def _run_stats(self) -> str:
        runs = self._load_runs()
        if not runs:
            return json.dumps({"error": "No run history found"})

        agent_counts   = Counter(r.get("agent_name", "unknown") for r in runs)
        shadow_counts  = Counter()
        total_tools    = 0
        total_iters    = 0
        total_shadows  = 0

        for r in runs:
            total_tools += len(r.get("tool_calls", []))
            total_iters += r.get("iterations", 0)
            shadow = r.get("shadow_events") or {}
            events = shadow.get("events_detected", 0)
            total_shadows += events
            if events > 0:
                code = shadow.get("shadow_code", "?")
                shadow_counts[code] += events

        return json.dumps({
            "total_runs":         len(runs),
            "total_tool_calls":   total_tools,
            "total_iterations":   total_iters,
            "total_shadow_events": total_shadows,
            "agents_by_usage":    dict(agent_counts.most_common()),
            "shadow_events_by_code": dict(shadow_counts),
            "avg_tools_per_run":  round(total_tools / max(len(runs), 1), 1),
            "avg_iterations":     round(total_iters / max(len(runs), 1), 1),
            "computed_at":        datetime.now(timezone.utc).isoformat(),
        }, indent=2)

    def _list_agents(self) -> str:
        if not AGENTS_JSON.exists():
            return json.dumps({"error": "agents.json not found"})
        try:
            agents = json.loads(AGENTS_JSON.read_text())
            return json.dumps({
                "total": len(agents),
                "agents": [
                    {
                        "name":    a["name"],
                        "type":    a["type"],
                        "profile": a["behavioral_profile"],
                        "shadow":  a.get("shadow_code", "?"),
                        "enabled": a.get("enabled", True),
                    }
                    for a in agents
                ],
            }, indent=2)
        except Exception as e:
            return json.dumps({"error": str(e)})


# ── CLI ───────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--task",  type=str, help="Run a task")
    parser.add_argument("--stats", action="store_true", help="Print run statistics")
    args = parser.parse_args()

    agent = MemoryAgent()

    if args.stats:
        print(agent._run_stats())
    elif args.task:
        result = agent.run(args.task)
        print(result["output"])
    else:
        # Default: show platform stats
        print(agent._run_stats())
